ip_forward: true
network_compression_threshold: 256
stats: a1db2331-2d37-4384-9f25-88c26ded543c
groups:
  Vol4n3:
  - admin
servers:
  survival:
    motd: '&2Survival'
    address: localhost:25500
    restricted: false
  skyblock:
    motd: '&2Skyblock'
    address: localhost:25600
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- query_port: 25565
  motd: '&2Mc.comuty.fr &3Survival &fand &6Skyblock'
  priorities:
  - survival
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 60
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
prevent_proxy_connections: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeechat.global
  - bungeechat.global.toggle
  - bungeechat.msg
  admin:
  - bungeechat.mute
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: -1
